### PR TITLE
Update master with QuizReview UI changes and Refactoring

### PR DESCRIPTION
**Pull request by jameelbrochu**
QuizReview UI enhancements:
- Display questions together with different colours for correct and wrong
- Activity now able to scroll
- Score added to quiz review page
- Fixed color text of quiz score dialog

Refactoring was done on major classes based off of feedback from the previous release and the newly added code from this release.

### CODE REVIEW

**Comment by j-suguma** [comment]
CI build dev:
image

tests:
image

SA:
image

**Review by coreylevine — APPROVED** [review]
Looks good! Everything has already been reviewed thoroughly in the PRs into dev. All the espresso tests pass. Assuming the manual testing passes and Jenkins passes, we can merge this pull request into Master.

**Comment by rekandiah** [comment]
Manual Tests:
1. Able to favorite a card and view it in the favorites deck: PASSED
2. View Favorites Card in the Card List page (Overview): PASSED
3. Able to Turn on/off hint mode: PASSED
4. Able to edit hints: PASSED
5. Text to Speech for Hint: PASSED
6. Able to Play a Quiz with Timer Mode: PASSED
7. Timer turns red when there's 10 seconds left and makes noise when 5 seconds left: PASSED
8. Deck is shuffled for regular and multiple choice deck: PASSED
9. Can add a new Deck of type Multiple Choice: PASSED
10. Can add new cards for the multiple choice deck: PASSED
11. Can edit a specific card in the mc deck: PASSED
12. Can delete a specific card in the mc deck: PASSED
13. Can delete a mc deck: PASSED
14. Able to view history of the passed 10 quiz results of a deck: PASSED

**Review by rekandiah — APPROVED** [review]

**Comment by j-suguma** [comment]
CI build for dev
image

tests:
image

static analysis, no critical warnings:
image

**Comment by svelupillai** [comment]
FavouritesOverviewTest passes:

image

**Comment by svelupillai** [comment]
FavouritesTest passes:

image

**Comment by svelupillai** [comment]
HintTest passes:

image

**Comment by svelupillai** [comment]
quizHistoryTest passes:

image

**Comment by svelupillai** [comment]
shuffleTest passes:

image

**Comment by rekandiah** [comment]
Edit a Multiple Choice Passes
a

**Comment by rekandiah** [comment]
Studying a MC deck passes
b

**Comment by svelupillai** [comment]
hintToggleCheckboxTest passes:

image

**Comment by rekandiah** [comment]
Check if last answer is selected when user does not select answer passes
c

**Pull request merged**
