### PR TITLE
Update Master

### PR DESCRIPTION
**Pull request by coreylevine**
Master will be updated with the new static analysis tool, the Hint Text to Speech feature, the delete and edit a multiple choice card feature and the quiz history feature.

### CODE REVIEW

**Comment by coreylevine** [comment]
I just ran the app in Dev and everything is working properly.

**Comment by rekandiah** [comment]
mc_study
mc_edit

**Comment by j-suguma** [comment]
CI build for dev:
image

tests:
image

Static Analysis:
image

**Comment by svelupillai** [comment]
The favouritesOverviewTest passes:

image

**Comment by svelupillai** [comment]
hintToggleCheckboxTest passes:

image

**Comment by coreylevine** [comment]
The features that we need to test manually (the list can be found in our PR policy on our wiki) all work as expected.

**Comment by svelupillai** [comment]
quizHIstoryTest passes:

image

**Comment by svelupillai** [comment]
shuffleTest passes:

image

**Pull request merged**
